build:
  version: "2.0"

cards:
  message: "Welcome to MyBank cards related QA APIs "
  contactDetails:
    name: "Sonali Babar - Product Owner"
    email: "sb@myybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267